const ERAS=[
{year:"1973",title:"电话第一次<br /><span>离开了墙。</span>",description:"它很重、很贵、很笨拙，但它第一次让电话可以跟着人走。",stat:"1.1 kg",statLabel:"早期移动电话重量",image:"https://commons.wikimedia.org/wiki/Special:FilePath/DynaTAC8000X.jpg",caption:"DYNATAC · FIRST GENERATION MOBILE PHONE",left:"MOBILE / 01G",right:"ANALOG / 1G"},
{year:"1983",title:"它开始<br /><span>真正进入生活。</span>",description:"商业化蜂窝网络出现，移动电话从实验设备变成了可以购买、可以携带的个人设备。",stat:"800 g",statLabel:"更轻的移动设备",image:"https://commons.wikimedia.org/wiki/Special:FilePath/DynaTAC8000X.jpg",caption:"DYNATAC 8000X · THE BRICK BECOMES MOBILE",left:"CELLULAR / 1G",right:"PORTABLE"},
{year:"1994",title:"文字，<br /><span>进入了手机。</span>",description:"IBM Simon 把电话、触控、日程与信息放进同一个设备，手机开始靠近“电脑”。",stat:"TOUCH",statLabel:"手机第一次接近智能终端",image:"https://commons.wikimedia.org/wiki/Special:FilePath/IBM_Simon_Personal_Communicator.png",caption:"IBM SIMON · PHONE MEETS COMPUTER",left:"TOUCH / PDA",right:"1994"},
{year:"2000",title:"手机开始<br /><span>拥有自己的世界。</span>",description:"彩屏、短信、游戏、音乐与相机，让手机从通信工具变成个人娱乐中心。",stat:"COLOR",statLabel:"屏幕开始表达更多",image:"https://commons.wikimedia.org/wiki/Special:FilePath/Nokia_3310_grey_front.jpg",caption:"NOKIA 3310 · THE PHONE BECOMES CULTURE",left:"SMS / GAME",right:"PERSONAL"},
{year:"2007",title:"屏幕，<br /><span>变成了入口。</span>",description:"触控、网页、地图、相机与应用，把手机推向掌上电脑时代。",stat:"MULTI-TOUCH",statLabel:"交互方式发生变化",image:"https://commons.wikimedia.org/wiki/Special:FilePath/Apple-iPhone-003.jpg",caption:"IPHONE · THE SCREEN BECOMES THE INTERFACE",left:"TOUCH / WEB",right:"2007"},
{year:"2015",title:"更多屏幕，<br /><span>更少边界。</span>",description:"显示、摄影、生物识别和移动支付逐渐融进同一个薄薄的矩形。",stat:"5.5 in",statLabel:"屏幕成为主要界面",image:"https://commons.wikimedia.org/wiki/Special:FilePath/Smartphone_%2816268692325%29.jpg",caption:"SMARTPHONE · EVERYTHING IN ONE SLAB",left:"CAMERA / PAY",right:"COMPUTE"},
{year:"2026",title:"下一步，<br /><span>是理解。</span>",description:"手机正在从响应指令的工具，变成更主动的个人计算入口。语音、视觉、文字与端侧 AI 开始融合。",stat:"AI",statLabel:"从操作走向意图",image:"https://commons.wikimedia.org/wiki/Special:FilePath/Pixel_10_front_%28Obsidian%29.svg",caption:"2026 · AI PHONE / FROM COMMAND TO INTENT",left:"VISION / VOICE",right:"INTENT"}
];
const COLLECTIONS=[["01","汽车","从机械动力到电动与智能化"],["02","电脑","从巨型计算机到个人 AI"],["03","相机","从胶片到计算摄影"],["04","电视","从黑白屏幕到流媒体"],["05","手表","从计时到腕上计算"]];
const $=id=>document.getElementById(id),clamp=(v,min=0,max=1)=>Math.min(Math.max(v,min),max),lerp=(a,b,t)=>a+(b-a)*t;
const progressBar=$("progress-bar"),evolution=document.querySelector(".evolution"),productImage=$("product-image"),ghostA=$("ghost-a"),ghostB=$("ghost-b"),stack=$("product-stack"),bg=$("evolution-bg"),eraIndex=$("era-index"),eraYear=$("era-year"),eraTitle=$("era-title"),eraDescription=$("era-description"),eraStat=$("era-stat"),eraStatLabel=$("era-stat-label"),eraCaption=$("era-caption"),detailLeft=$("detail-left"),detailRight=$("detail-right"),eraProgress=$("era-progress"),explodeLines=$("explode-lines"),dots=$("era-dots");
function renderDots(){dots.innerHTML=ERAS.map((e,i)=>`<button type="button" aria-label="跳到 ${e.year}" data-index="${i}"></button>`).join("");dots.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{const i=+b.dataset.index;const target=evolution.offsetTop+(evolution.offsetHeight-innerHeight)*(i/(ERAS.length-1));scrollTo({top:target,behavior:"smooth"})}))}
function renderTimeline(){document.getElementById("timeline-list").innerHTML=ERAS.map((e,i)=>`<article class="timeline-item"><strong>${e.year}</strong><div><h3>${e.title.replace(/<[^>]+>/g,"")}</h3><p>${e.description}</p></div><em>0${i+1} / 07</em></article>`).join("")}
function renderCollections(){document.getElementById("collection-grid").innerHTML=COLLECTIONS.map(([i,n,d])=>`<article class="collection-card"><span class="index">${i}</span><strong>${n}</strong><span>${d}</span></article>`).join("")}
function setEra(index,local,global){const from=ERAS[index],to=ERAS[Math.min(index+1,ERAS.length-1)],changing=index<ERAS.length-1&&local>.52,current=changing?to:from,transition=index<ERAS.length-1?clamp((local-.38)/.24):0;eraIndex.textContent=String((changing?index+2:index+1)).padStart(2,"0");eraYear.textContent=current.year;eraTitle.innerHTML=current.title;eraDescription.textContent=current.description;eraStat.textContent=current.stat;eraStatLabel.textContent=current.statLabel;eraCaption.textContent=current.caption;detailLeft.textContent=current.left;detailRight.textContent=current.right;if(productImage.dataset.src!==current.image){productImage.dataset.src=current.image;productImage.src=current.image}const angle=lerp(-10,10,Math.sin(global*Math.PI*1.5)*.5+.5),scale=lerp(.86,1.05,Math.sin(local*Math.PI)*.12+.5),y=Math.sin(global*Math.PI*2)*-16;productImage.style.transform=`translateY(${y}px) rotateY(${angle}deg) rotateZ(${lerp(-3,3,local)}deg) scale(${scale})`;productImage.style.opacity=1-transition*.35;ghostA.src=from.image;ghostB.src=to.image;ghostA.style.opacity=transition*.34;ghostB.style.opacity=transition*.26;ghostA.style.transform=`translate(${transition*-70}px,${transition*-26}px) rotateZ(${transition*-6}deg) scale(${1+transition*.05})`;ghostB.style.transform=`translate(${transition*70}px,${transition*34}px) rotateZ(${transition*6}deg) scale(${1+transition*.08})`;explodeLines.style.opacity=transition>.2&&transition<.95?Math.min(transition*1.8,1)*.55:0;stack.style.transform=`translateY(-50%) scale(${1+Math.sin(local*Math.PI)*.025})`;bg.style.background=current.year==="2026"?"radial-gradient(circle at 68% 48%,rgba(109,119,255,.18) 0,rgba(185,108,255,.08) 24%,#f1f1f0 56%,#e9e9e7 100%)":"radial-gradient(circle at 67% 48%,#fff 0,#f5f5f2 37%,#eeeeec 100%)";dots.querySelectorAll("button").forEach((b,i)=>b.classList.toggle("active",i===(changing?index+1:index)))}
function update(){const maxScroll=document.documentElement.scrollHeight-innerHeight,pageProgress=maxScroll>0?scrollY/maxScroll:0;progressBar.style.width=`${pageProgress*100}%`;const rect=evolution.getBoundingClientRect(),range=Math.max(evolution.offsetHeight-innerHeight,1),progress=clamp(-rect.top/range),position=progress*(ERAS.length-1),index=Math.min(Math.floor(position),ERAS.length-2),local=position-index;eraProgress.style.width=`${progress*100}%`;setEra(index,local,progress)}
renderDots();renderTimeline();renderCollections();addEventListener("scroll",update,{passive:true});addEventListener("resize",update);addEventListener("load",update);update();
